spring.application.name=somedatademo
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=devuser
spring.datasource.password=1234

#spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
#spring.datasource.username=devuser
#spring.datasource.password=1234


logging.level.root=warn
#logging configs
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace


#Congigure for auto creae
#spring.jpa.hibernate.ddl-auto=create

#Spring security
spring.security.user.name=dodos
spring.security.user.password=1234

#Some data
countries=USA,UK,Canada,France,Germany,Italy,Spain,Portugal,Sweden,Finland,Denmark,Norway,Poland,Russia,China,Japan,Korea,India,Australia,New Zealand
programmingLanguages=Java,Python,JavaScript,TypeScript,Angular,React,Vue,Node,Express,JavaEE
operatingSystems=Windows,MacOS,Linux,Unix,Android,iOS
